spring.application.name=Tatkal

#spring.datasource.url=jdbc:mysql://localhost:3306/tatkal
#spring.datasource.username=root
#spring.datasource.password=root


spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tatkal}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

server.port=${PORT:10000}
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.initialization-fail-timeout=1
spring.datasource.hikari.connection-timeout=5000

razorpay.key-id=${RAZORPAY_KEY_ID:dummy}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:dummy}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:dummy}

spring.config.import=optional:file:.env[.properties]
