spring.application.name=Tatkal
server.port=8070

spring.datasource.url=jdbc:mysql://localhost:3306/tatkal
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Force Hikari to fail fast if the database is unreachable
spring.datasource.hikari.initialization-fail-timeout=1
spring.datasource.hikari.connection-timeout=5000


